services:
  load-balancer:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - business-service
    networks:
      - proximity-service-network

  business-service-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: business-service-user
      POSTGRES_PASSWORD: business-service-password
      POSTGRES_DB: business_db
    ports:
      - 5432
    networks:
      - proximity-service-network

  business-service:
    build:
      dockerfile: business-service/Dockerfile
    ports:
      - 8080
    networks:
      - proximity-service-network

  init-businesses:
    image: curlimages/curl:latest
    volumes:
      - ./init-businesses.sh:/init.sh:ro
    entrypoint: [ "sh", "/init.sh" ]
    depends_on:
      - business-service
    networks:
      - proximity-service-network


networks:
  proximity-service-network:
    driver: bridge