spring:
  datasource:
    url: jdbc:postgresql://business-service-db:5432/business_db
    username: business-service-user
    password: business-service-password
business-initializer:
  enabled: true
kafka-connect:
  debezium:
    host: business-service-debezium
    port: 8083
    user: debezium_user
    password: dbz
    database-host: business-service-db
    database-name: business_db