CREATE ROLE debezium_user WITH LOGIN PASSWORD 'dbz' REPLICATION;
GRANT CONNECT ON DATABASE business_db TO debezium_user;
GRANT CREATE ON DATABASE business_db TO debezium_user;
GRANT USAGE ON SCHEMA public TO debezium_user;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO debezium_user;